### ISSUE TITLE
Doesn't work at all well

### ISSUE THREAD

**Issue by IanAdd** [ShadowAya/anchor-card#2]
It reloads the page instead of simply scrolling to the relevant card.
The delay feature tries to help waiting for the 'reload' but variability on the view's cards speed of refresh make it unreliable or feel incredibly unresponsive.

Nice idea but currently unusable for me.

**Comment by ShadowAya** [comment]
The card only reacts to itself being loaded in with an anchor in the URL, and it only replaces the current URL when done scrolling. I've never had it reload the page.

Could you send a screen recording? You can also try to disable the `remove_anchor` option, which does the history replace.

**Comment by ShadowAya** [comment]
Closing - If the issue persists for anyone, please open a new issue. The card is not responsible for refreshing the page, I'd need a repro to analyze.
