### ISSUE TITLE
The remove_anchor option leaves '?' in the URL

### ISSUE THREAD

**Issue by robertwigley** [ShadowAya/anchor-card#3]
As the title says, if you're making use of the `remove_anchor` option, it leaves the question mark '?' in the URL. Mainly cosmetic, but I thought it was worth mentioning.

**Comment by ShadowAya** [comment]
Yep, know about that. Will remove the useless question mark next update, makes sense. Thanks for the suggestion once again!

**Comment by ShadowAya** [comment]
Implemented on [v2.4](https://github.com/ShadowAya/anchor-card/releases/tag/v2.4)
