### ISSUE TITLE
Format of URL with anchor is nonstandard

### ISSUE THREAD

**Issue by robertwigley** [ShadowAya/anchor-card#4]
I am not sure if this is intentional and needed in order for Home Assistant to parse the integration, but rather than using `https://www.address.com/page?anchor=anchor_name` the normal format for accessing an anchor is `https://www.address.com/page#anchor_name`

**Comment by ShadowAya** [comment]
Using client side routing would make more semantical sense, true. I wanted to use a query parameter to be sure not to break anything, but it wouldn't be a bad idea to add an option to use this instead. Thanks for the suggestion!
