### ISSUE TITLE
Grey line

### ISSUE THREAD

**Issue by pavlovs-hub** [ShadowAya/anchor-card#5]
Hi, how can I hide this grey line?

![2024-02-28_214436](https://github.com/ShadowAya/anchor-card/assets/94526141/7ef13715-d453-4b92-bde4-1b6e25345a75)

> type: custom:anchor-card
> anchor_id: top
> negative_margin: 0px
> offset: -50
> timeout: 0ms

**Comment by ShadowAya** [comment]
Fixed on [v2.4](https://github.com/ShadowAya/anchor-card/releases/tag/v2.4), thanks for reporting! Let me know if the fix works for you, it was the theme's border showing

**Comment by ShadowAya** [comment]
Also noticed there was a mistake in README, values are only numeric (negative_margin and timeout should both be just `0`), apologies!

Please fix your config, although it doesn't make a difference for you because an invalid value will default to zero

**Comment by pavlovs-hub** [comment]
Thanks for your reply) 
I see this if set negative_margin to 0

```
type: custom:anchor-card
anchor_id: light
negative_margin: 0
offset: -50
timeout: 0
```

![Screenshot_20240229-000734_Home Assistant](https://github.com/ShadowAya/anchor-card/assets/94526141/9aa74198-6cd5-4aa7-bdd3-8330ad076b37)

**Comment by pavlovs-hub** [comment]
```
anchor_id: light
type: custom:anchor-card
negative_margin: -30
offset: -60
timeout: 0
```

This works great! Is it possible to add immediately scroll instead of smooth?

**Comment by ShadowAya** [comment]
Gonna release that option with the next update, good suggestion. Closing now!
