### ISSUE TITLE
How to use the card?

### ISSUE THREAD

**Issue by erkr** [ShadowAya/anchor-card#7]
Hi

I really like the proposition of this card. thanks for all the efforts put into that. 
 But I failed to use it. Probably a misconception how to use it from my side. 
Installation via HACS and creating urls to navigate works fine. But the page roughly scrolls down one card, not to the anchor card inserted way below.
So a few questions: 
- Where to insert anchor cards? Above, or below the card of interest? Or even inside i.e a stack card?
- I was using a Sidebar view type? Any restrictions on view types?
- I'm using several custom:state-switch cards in my view. Is that ok?
Best Eric

**Comment by ShadowAya** [comment]
The card scrolls until it is in view, so where you see it in edit mode is where it will align itself to the top of the viewport

**Comment by erkr** [comment]
Thanks for the quick answer, but that is not what seems to happen in my Sidebar view. Will have another look.

**Comment by erkr** [comment]
I got it working! I had to increase the delay. All those custom:state-switch cards need some time

**Comment by ShadowAya** [comment]
Yep, also had some cards that are slow to render. Thanks for using my project by the way!
