### ISSUE TITLE
Add to existing card? It takes up a space on my dashbaord?

### ISSUE THREAD

**Issue by deanfourie1** [ShadowAya/anchor-card#8]
IS there a way to implement this card without it taking up an additional space on my dashbaord.

Right now I added it as an additional card, however it created an empty space pushing everything down slightly.

Any way to get around this?

Thanks

**Comment by ShadowAya** [comment]
Adjust the `negative_margin` value, the default might not be enough for you

**Comment by deanfourie1** [comment]
> Adjust the `negative_margin` value, the default might not be enough for you

Hmm thanks, but this doesnt seem to make a difference.

**Comment by deanfourie1** [comment]
In fact, changing negative margin doesn't seem to make any difference at all.

Also tested with incognito incase of caching, no difference.

**Comment by deanfourie1** [comment]
Here is another issue I am facing.


https://github.com/ShadowAya/anchor-card/assets/71812804/601223d7-e0a9-4bda-bb6e-3a2490ff3087

**Comment by ShadowAya** [comment]
Sorry for the late reply, I'm not sure what causes this. The card itself is gonna have the negative margin, but maybe the dashboard theme you're using is messing with it.

If you want to, you can use [card mod](https://github.com/thomasloven/lovelace-card-mod) to fix the spacing yourself, or if you know your way around HTML, you can find the element that is creating the extra space and send it here - I'll have a look, but it's impossible for me to replicate unfortunately!

**Comment by deanfourie1** [comment]
Thanks, I would really love to get this working but I cannot live with the spaces as it just triggers my OCD.

I did a inspect element of the spaced area.


```
<div style="" class="card"> <!--?lit$887706585$--><anchor-card><ha-card class="type-custom-anchor-card" style="margin: -10px 0px; border-width: 0px;"><card-mod slot="none" card-mod-type="card" style="display: none;"><!---->
      <style>
        <!---->
      <!----></style>
    </card-mod></ha-card></anchor-card> </div>
```

Here, you can see an example of the spacing of how it should be and how it looks

Thank you

**Comment by deanfourie1** [comment]
Bump, this is still an issues and makes this integration unusable for me.

Guess its not an issue for anyone else.

**Comment by ShadowAya** [comment]
It's your theme adding a space above the level of the card itself, some sort of gap or something, I think. When in inspect element, you can hover the gap and see which element it's coming from

**Comment by deanfourie1** [comment]
Could you help me fix this? I would be very grateful. I really want to start using this but I really cant as it just makes my dashboard look terrible.

This is the element contents of the space.

```
<div style="--column-size: 4; --row-size: auto;" class="card   "> <!--?lit$789745792$--><hui-card><anchor-card><ha-card class="type-custom-anchor-card" style="margin: -10px 0px; border-width: 0px;"><card-mod slot="none" card-mod-type="card" style="display: none;"><!---->
      <style>
        <!---->
      <!----></style>
    </card-mod></ha-card></anchor-card></hui-card> </div>
```

Can I use card-mod to somehow set like negative margins?

**Comment by ShadowAya** [comment]
Go into element selection mode in inspect element, hover the space, and check which part exactly creates the space, you can also check if that's inside or outside the card. You can also see the computed size of that element (including margins and paddings)

**Comment by deanfourie1** [comment]
It appears that when I disable this rule, the card appears to disappear, or for the spacing to be correct and it works as expected.

![Screenshot 2024-07-07 004210](https://github.com/ShadowAya/anchor-card/assets/71812804/8142fa59-0d6d-43c4-ab26-83b2ce00039f)

**Comment by ShadowAya** [comment]
This appears to be a dashboard/theme specific issue. You can use card-mod to add custom css to rewrite this value.

You can share your theme and dashboard (anything that could modify the default behaviors), that would be helpful. Thank you!

I'm gonna close the issue now.

EDIT: leaving this open for a bit

**Comment by deanfourie1** [comment]
I can share anything you need just want to get this working.

I've tried to overwrite the classes that I think are causing the issue with card-mod but no luck!

**Comment by eporsche** [comment]
I am having the same issue. Could be sections view related. In masonry view  the card doesnt add additional space.

**Comment by ShadowAya** [comment]
I will try to add more margin and height related CSS this week, as well as an option to adjust the scroll transition speed (unrelated). I think the most I can do is add height, max height and some transform rules, or try to target the parent's styles with JS as a last resort.

**Comment by ShadowAya** [comment]
Pushed an [update](https://github.com/ShadowAya/anchor-card/releases/tag/v3.2), @deanfourie1 can you check if the card's scaling is fixed?

**Comment by ShadowAya** [comment]
By the way, have you increased the `negative_margin` value? The cards would overlap, sure, but that shouldn't be an issue in this case

**Comment by deanfourie1** [comment]
Still does not appear to be working for me,

Using code

```
          - type: custom:anchor-card
            anchor_id: lights
            negative_margin: 100
            timeout: 200
            offset: -5
            backout: true
```

Still the gap is the same, 

Thanks for the update.

**Comment by eporsche** [comment]
Same here - the gab is still present. @deanfourie1 are you using the section view as well?
@ShadowAya thx for your effort! This integration is very useful!

**Comment by ShadowAya** [comment]
You're right, it only takes up space in the sections view. I didn't notice the initial comment sorry!
I'll take a look

**Comment by ShadowAya** [comment]
Home Assistant is doing its hardest to enforce its sizing of any part of the grid, this is a tough one. Even if the card and its parent container have a 0x0 size, the grid still creates space

**Comment by ShadowAya** [comment]
@deanfourie1 @eporsche I figured it out, please check if [v3.3](https://github.com/ShadowAya/anchor-card/releases/tag/v3.3) fixes the issue for you. Also keep in mind the two disclaimers

**Comment by deanfourie1** [comment]
Damn sorry I probably should have mentioned that. Will try test now

**Comment by eporsche** [comment]
@ShadowAya works now - thx! Finally I can use badges to navigate to "more info" sections without manual scrolling. Nice! 👍

**Comment by deanfourie1** [comment]
Yes I can confirm this is now working! Thank you for this! This has been long awaited.

Thanks so much for your efforts!

**Comment by ShadowAya** [comment]
Thank you both for bringing this to my attention. At first I didn't notice that it was only happening on sections, my bad. Good that it's now solved
